language: scala

scala:
- 2.11.8

env:
  global:
    secure: g4qlrLMEa+tfO+ab5u+gizHYfop32wOheu89skNGjwcPn34RTsOvc2cKWJ8KfmfkgQDyvHWPOKctjl5vamZs/mjGakLGRpnLx/Sa4lE+quYbktGDDI51pUuf94Asl8MQfNYWG7Ks88BzjMmJP4lBzfHIMYukUL7P2ZrelqI6tGzBiGDVD9NjHjN1TppRX2nASuxWNCidmtuJy7mABzKbZQzXedAwA/kWADiUEP0vS6ewcfIwe7RCh9LtST8uCPTbBVzaAWgRiw0LvVx82xZQDVauj9qHGbpd7hbpJjQm5PVBkPHgmnSwAY/mWk5XO/99Fg6KahCeKbnhYBh1BgqxrnVdkvezMUWioUaHA1Qbvj9X6TUpyR5K8i6XiaDQOF7wJgXNzavUZxMiyDdMfYzdgAxndr78f1EWcbSoVRM1advQAKoLNv9h0YSCbZyEzHaEzvA3VwMHcZ4Ctq3cKwS4BzZBNJrTUnH/EEIuu23N6JdXPPFTcXnV0MU1OmlC7W61e/nrSTn6GKPFEtK87taQrABkWZYnPQQihd21SNzLUD0YGYtImZFW9b6sd2DHuA1kXiiWUjIx+aYLc5dT5+CLNl9n43uG9cIGLXwfquVN3QCmHxh3kWzIQgTApIQ+0aXJDWXa9oCbpXkS5NDIa0Mj7d4/dMQuswIKWzHSz3PeasY=
